version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    networks:
      - vpn_network

  wireguard:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      WG_HOST: ${WG_HOST}
      PASSWORD: ${WG_PASSWORD}
    volumes:
      - wireguard-config:/etc/wireguard
    ports:
      - '51820:51820/udp'
      - '51821:51821/tcp'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - vpn_network

  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    volumes:
      - ./v2ray:/etc/v2ray
    ports:
      - '12399:12399'
    restart: unless-stopped
    command: run -config /etc/v2ray/config.json
    networks:
      - vpn_network

networks:
  vpn_network:


volumes:
  npm-data:
  npm-letsencrypt:
  wireguard-config:
